### ISSUE TITLE
Simplifying the delegation solution

### ISSUE THREAD

**Issue by pmoura** [koryonik/logtalk-experiments#2]
The `familytreev2` can be simplified by declaring that it implements the `family` protocol.

Also, if the intention is to have the `familytreev2` object as a singleton, the definitions of the `male/1`, `female/1`, and `parent/2` predicates can be optimized by calling the `family/1` predicate locally instead of sending a message to _self_.

**Comment by koryonik** [comment]
Fixed in @2b861b95c6692081db3b6c7dac7a31f546c8a1c5
