### ISSUE TITLE
`benchmarks/benchmark.lgt` misleading results

### ISSUE THREAD

**Issue by pmoura** [koryonik/logtalk-experiments#5]
The benchmark goal uses `call/1`, which _interprets_ its argument at runtime. Thus, instead of measuring the performance of a call, it's measuring the performance of compiling a goal **plus** the performance of the goal itself.

**Comment by koryonik** [comment]
In @ da922467646c8438e84669587c3d5b8b074a62c9 , I added a third bench testing a plain predicate wrapping logtalk message call (`logtalk_obj_simple_wrapped/0`), to avoid top-level interpretation. Result are different (see logtalk-experiments/benchmarks/README.md), but gap with plain prolog always significant. I tried to replace the `call/1` by directly predicate / message call, but result are the same. Maybe I don't understand what you mean or SWI lack some optimizations ?

**Comment by pmoura** [comment]
The Logtalk compiler doesn't compile plain Prolog code included in Logtalk source files. Plain Prolog code is simply copied as-is to the generated code. Thus, the processing of the message sending goal occurs only at runtime, not at compile time. This includes the messages sent from the `loader.lgt` file as it contains a Prolog `initialization/1` directive.

**Comment by pmoura** [comment]
Fixed in #6.

**Comment by pmoura** [comment]
Closing this issue as you already merged the pull request that fixes the tests.
